language: go

go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - tip

before_script:
  - mysql -u root -e 'create database `cachedfetcher`'
  - mysql -u root -e 'grant all on cachedfetcher.* to travis'
  - mysql -u travis cachedfetcher < _data/setup_mysql.sql
  - psql -c 'create database cachedfetcher' -U postgres
  - psql -U postgres cachedfetcher < _data/setup_psql.sql


script:
  - make test
  - make test.example.mysql MYSQL="travis@/cachedfetcher"
  - make test.example.psql PSQL="user=postgres dbname=cachedfetcher"
